name: calendar-handler
description: Handle calendar queries using Ollama classification
priority: 8
trigger:
  source: inbox
  classifier: ollama
  model: qwen2.5:7b
  intents:
    - calendar_today
    - calendar_upcoming
    - calendar_query
    - calendar_free
    - not_calendar
pipeline:
  - action: gate
    condition: "{{.intent}} == not_calendar"
    stop: true
  - action: calendar_dispatch
    output: response
  - action: reply
    message: "{{.response}}"
