name: calendar-handler
description: Handle calendar queries via /cal slash command
priority: 8
trigger:
  source: inbox
  pattern: "^/cal(?:\\s+(.*))?$"
  extract:
    - query
pipeline:
  - action: calendar_dispatch
    input: "{{.query}}"
    output: response
  - action: reply
    message: "{{.response}}"
