name: gtd-handler
description: Handle GTD queries via /gtd slash command using Things 3 via MCP
priority: 10
trigger:
  source: discord
  slash_command: gtd
  classifier: ollama
  model: qwen2.5:7b
  intents:
    - gtd_show_today
    - gtd_show_inbox
    - gtd_add_inbox
  prompt: |
    Classify this GTD task management request from a /gtd slash command.

    Intents:
    - gtd_show_today: User wants to see today's tasks (e.g., "today", "what's on my list", "tasks", "show", "list")
    - gtd_show_inbox: User wants to see inbox items (e.g., "inbox", "what's waiting", "captured", "unsorted")
    - gtd_add_inbox: User wants to add an item to inbox (e.g., "add buy milk", "capture call doctor", "remember to...")

    Answer with ONE intent name only, no explanation.
pipeline:
  - action: gtd_dispatch_things
    output: response
  - action: reply
    message: "{{.response}}"
