name: gtd-handler
description: Handle GTD queries via /gtd slash command
priority: 10
trigger:
  source: inbox
  slash_command: gtd
  classifier: ollama
  model: qwen2.5:7b
  intents:
    - gtd_show_today
    - gtd_show_inbox
    - gtd_show_logbook
    - gtd_add_inbox
    - gtd_complete
  prompt: |
    Classify this GTD query. The user invoked /gtd, so they want task management.

    Intents:
    - gtd_show_today: Asks for today's tasks (e.g., "today", "what's on my list", "tasks")
    - gtd_show_inbox: Asks for inbox items (e.g., "inbox", "what's waiting")
    - gtd_show_logbook: Asks for completed tasks (e.g., "done", "completed", "logbook")
    - gtd_add_inbox: Adding an item (e.g., "add buy milk", "capture call doctor")
    - gtd_complete: Completing a task (e.g., "complete X", "done with X")

    Answer with ONE intent name only.
pipeline:
  - action: gtd_dispatch
    output: response
  - action: reply
    message: "{{.response}}"
