name: gtd-handler
description: Handle GTD queries using Ollama classification
priority: 10
trigger:
  source: discord
  classifier: ollama
  model: qwen2.5:7b
  intents:
    - gtd_show_today
    - gtd_show_inbox
    - gtd_add_inbox
    - gtd_complete
    - not_gtd
pipeline:
  - action: gate
    condition: "{{.intent}} == not_gtd"
    stop: true
  - action: gtd_dispatch
    output: response
  - action: reply
    message: "{{.response}}"
